version: 0.0
os: linux
files:
  - source: pollme
    destination: /home/ec2-user/environment/DevopsProj
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
  AfterInstall:
    - location: scripts/after_install.sh
