version: 0.0
os: linux
files:
  - source: pollme
    destination: /home/ubuntu/environment/ls/DevopsProj
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
  AfterInstall:
    - location: scripts/after_install.sh
