version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt # Install dependencies needed for running the static analysis
  pre_build:
    commands:
      - python --version
      - pylint --disable=C $CODEBUILD_SRC_DIR/*.py
      - pylint --disable=C,W0611,R1705,R0903,E1101,W0105,W0612,E0307,E1136,E1128,W0125 $CODEBUILD_SRC_DIR/*/*.py
     
artifacts:
  files:
    - '**/*'